name: Build Dist

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      # ضغط مجلد dist
      - name: Zip dist folder
        run: zip -r dist.zip dist

      # رفع الملف كـ artifact
      - name: Upload dist artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-file
          path: dist.zip
